### ISSUE TITLE
Investigate keyberon panic

### ISSUE THREAD

**Issue by borisfaure** [borisfaure/cnano-rs#1]
```
101.153372 INFO  Event: "Release(3, 3)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
103.121184 INFO  Event: "Press(1, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
103.221895 INFO  Event: "Release(1, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
104.690506 INFO  Event: "Press(1, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
104.772593 INFO  Event: "Release(1, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
104.954061 INFO  Event: "Press(0, 6)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
104.998866 INFO  Event: "Release(0, 6)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
105.727740 INFO  Event: "Press(0, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
105.829186 INFO  Event: "Release(0, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
106.390869 INFO  Event: "Press(2, 8)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
106.490993 INFO  Event: "Release(2, 8)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
107.797570 INFO  Event: "Press(1, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
107.864400 INFO  Event: "Release(1, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
109.248258 INFO  Event: "Press(1, 0)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
109.370861 INFO  Event: "Release(1, 0)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
109.973145 INFO  Event: "Press(3, 0)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
110.050818 INFO  Event: "Release(3, 0)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
110.570349 INFO  Event: "Press(3, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
110.667468 INFO  Event: "Release(3, 2)"
└─ firmware::side::full_duplex_comm::{async_fn#0} @ firmware/src/side.rs:222
111.041951 INFO  Event: "Press(3, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
111.242329 INFO  Layer: 2
└─ firmware::layout::layout_handler::{async_fn#0} @ firmware/src/layout.rs:153
111.250714 INFO  Temporarily setting solid color: 2
└─ utils::rgb_anims::{impl#3}::temporarily_solid_color @ utils/src/rgb_anims.rs:344
111.250973 INFO  Current animation: SolidColor(0)
└─ utils::rgb_anims::{impl#3}::temporarily_solid_color @ utils/src/rgb_anims.rs:345
111.251192 INFO  Saving animation: SolidColor(0)
└─ utils::rgb_anims::{impl#3}::temporarily_solid_color @ utils/src/rgb_anims.rs:350
111.251378 INFO  Already saved animation: Some(SolidColor(0))
└─ utils::rgb_anims::{impl#3}::temporarily_solid_color @ utils/src/rgb_anims.rs:354
111.279103 INFO  Event: "Press(1, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
111.378733 INFO  Event: "Release(1, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
111.455215 INFO  Event: "Release(3, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
111.459221 INFO  Layer: 0
└─ firmware::layout::layout_handler::{async_fn#0} @ firmware/src/layout.rs:153
111.471939 INFO  Event: "Press(3, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
111.475791 INFO  Event: "Release(3, 7)"
└─ firmware::keys::matrix_scanner::{async_fn#0} @ firmware/src/keys.rs:71
111.479031 ERROR panicked at /home/boris/.cargo/git/checkouts/keyberon-6cb2b7a38d87b644/5f94202/src/layout.rs:298:32:
attempt to subtract with overflow
```

**Comment by borisfaure** [comment]
https://github.com/borisfaure/keyberon/blob/shifted_seq/src/layout.rs#L298

**Comment by borisfaure** [comment]
After more than 6 hours:
```
23074.482710 INFO  new waiting state with timeout: 200, delay:1, self.waiting.is_some(): false
└─ keyberon::layout::{impl#14}::do_action @ /home/boris/stuff/kb/keyberon/src/layout.rs:693
23074.600748 INFO  HoldTap: release event after delay: since=1, delay=1, timeout=83
└─ keyberon::layout::{impl#5}::tick @ /home/boris/stuff/kb/keyberon/src/layout.rs:306
23074.601143 INFO  removing waiting state
└─ keyberon::layout::{impl#14}::waiting_into_tap @ /home/boris/stuff/kb/keyberon/src/layout.rs:488
23075.938043 INFO  new waiting state with timeout: 200, delay:1, self.waiting.is_some(): false
└─ keyberon::layout::{impl#14}::do_action @ /home/boris/stuff/kb/keyberon/src/layout.rs:693
23076.034834 INFO  HoldTap: release event after delay: since=1, delay=1, timeout=105
└─ keyberon::layout::{impl#5}::tick @ /home/boris/stuff/kb/keyberon/src/layout.rs:306
23076.035218 INFO  removing waiting state
└─ keyberon::layout::{impl#14}::waiting_into_tap @ /home/boris/stuff/kb/keyberon/src/layout.rs:488
23076.310758 INFO  new waiting state with timeout: 200, delay:1, self.waiting.is_some(): false
└─ keyberon::layout::{impl#14}::do_action @ /home/boris/stuff/kb/keyberon/src/layout.rs:693
23076.508696 INFO  removing waiting state
└─ keyberon::layout::{impl#14}::waiting_into_hold @ /home/boris/stuff/kb/keyberon/src/layout.rs:474
23076.630197 INFO  new waiting state with timeout: 200, delay:1, self.waiting.is_some(): false
└─ keyberon::layout::{impl#14}::do_action @ /home/boris/stuff/kb/keyberon/src/layout.rs:693
23076.631315 ERROR HoldTap: release event before delay: since=2, delay=1, timeout=199
└─ keyberon::layout::{impl#5}::tick @ /home/boris/stuff/kb/keyberon/src/layout.rs:299
23076.631705 ERROR panicked at /home/boris/stuff/kb/keyberon/src/layout.rs:313:32:
attempt to subtract with overflow
└─ panic_probe::print_defmt::print @ /home/boris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/panic-probe-0.3.2/src/lib.rs:104
Error: An ARM specific error occurred.
```
